import {
  APP_LOGGING as APP_LOGGING_VAL,
  CHATKITTY_APP_ID,
  CHATKITTY_INSTANCE,
  CHATKITTY_MEASUREMENT_ID,
  FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN,
  FIREBASE_DATABASE_URL,
  FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET,
} from 'react-native-dotenv';

export default {
  FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN,
  FIREBASE_DATABASE_URL,
  FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID,
  CHATKITTY_APP_ID,
  CHATKITTY_MEASUREMENT_ID,
  CHATKITTY_INSTANCE,
  APP_LOGGING: APP_LOGGING_VAL !== 'false' ? true : false,
};
