import {
  APP_LOGGING,
  CHATKITTY_APP_ID,
  CHATKITTY_INSTANCE,
  CHATKITTY_MEASUREMENT_ID,
  FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN,
  FIREBASE_DATABASE_URL,
  FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET,
} from 'react-native-dotenv';

export const APP_LOGGIBNG = APP_LOGGING !== 'false' ? true : false;

export {
  FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN,
  FIREBASE_DATABASE_URL,
  FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID,
  CHATKITTY_APP_ID,
  CHATKITTY_MEASUREMENT_ID,
  CHATKITTY_INSTANCE,
};
